---
title: "Flex Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r}
library(flexdashboard)
library(p8105.datasets)
library(plotly)
library(tidyverse)
data("ny_noaa")
```

Column {data-width=650}
-----------------------------------------------------------------------

### Maximum Temperature (tenths of degrees C) Each Day in 1981 in Weather Station USW00094794

```{r}
ny_noaa |>
  filter(id == "USW00094794",
         date < "1982-01-01") |>
  drop_na() |>
  mutate(date = as.character(date),
         tmax = as.numeric(tmax)) |>
  plot_ly(x = ~date, y = ~tmax, type = "bar", colors = "viridis")
```


Column {data-width=350}
-----------------------------------------------------------------------

### Snowfall(mm) vs. Precipitation(tenths of mm) in 1981

```{r}
ny_noaa |>
  filter(date < "1982-01-01",
         snow > 0) |>
  plot_ly(
    x = ~snow, y = ~prcp, type = "scatter", mode = "markers", alpha = 0.5)
```

### Snowfall(mm) in 1981 snow days

```{r}
ny_noaa |>
  filter(date < "1982-01-01",
         snow > 0) |>
  mutate(date = as.character(date)) |>
  plot_ly(x = ~date, y = ~snow, 
          type = "box", alpha = 0.5)
```

