---
title: "Resume"
output: 
  html_document:
    toc: true
    toc_float: true

---

# Basic Information
  Email: xt2288@cumc.columbia.edu 
  Tel.:+1 (217)9799813
  Add.: NY, NY

# EDUCATION
Columbia University (Mailman School of Public Health) (New York, NY)

- Aug 2023- May 2025(Expected) 
- Major: Master of Science in Biostatistics
- Relevant Coursework: Data Science, Biostatistical Methods, Probability, Epidemiology

University of Illinois, Urbana-Champaign (Urbana, IL)

- Aug 2019- May 2023
- Major: Bachelor of Science in Chemistry and Statistics
- Honor: Dean's List (2020-2023); Craig P. Baskin Endowed Undergraduate Chemistry Scholarship (2022-2023); J. J. Lagowski Scholarship in Chemistry(2022-2023); Highest Distinction in Statistics
- Relevant Coursework: Calculus III, Statistics and Probability, Linear Algebra, Statistics Programming Methods, Methods of Applied Statistics, Statistical Data Management, Applied Machine Learning, Statistical Modelling, Biostatistics, Public Health, Epidemiology, etc.

# WORK & RESEARCH EXPERIENCE
UIUC Statistics Department (Urbana, IL)
- Statistics Grader 
- Feb 2022- May 2023 
- Responsible for marking the assignments of Biostatistics Class for graduate students
- Developed indepth understanding of biostatistics and trained R intensively by running students’ codes to check their feasibility

Applied Technologies for Learning in the Arts & Sciences in UIUC (Urbana, IL) 
- Data Analyst 
- Aug 2022- Dec 2022 
- Gain profound insights into how to identify, analyze, and interpret trends and patterns in data in real-world scenarios
- Build a working foundation of modern data analysis tools and techniques such as data discovery, identification, and cleansing as well as data visualizations using Tableau
- Collaborate with a distributed team to find trends and correlations for clients


Swatch Group (Shanghai) (Shanghai, China) 
- Data Analyst Intern
- Jan 2021- Jun 2021 
- Led internal processes and contract management in the company’s leading brand-TISSOT
- Deeply involved in company research, industry research, market analysis, data correction, and data analytics using Excel 

Shanghai Jiahua Chemical Company (Shanghai, China) 
- Research and Development Intern 
- Aug 2020- Dec 2020 
- Wrote a voluminous literature review on experiment-related expertise such as polyether, polyester amine, and hard foam
- Accomplished the preparation of formulas and the development of foam required for production

# EXTRACURRICULAR ACTIVITIES
Statistics Department, UIUC
- Statistics Ambassador
- Represented the department in recruitment events, welcome events, campus fairs, etc.
- Answered questions from current and prospective statistics students and mentored freshmen on campus Carle Foundation Hospital

Student Volunteer
- Administered voluntary work mainly in the Surgery Center and Administrative Office

International Students In Pre-Health
- Co-founder & Treasurer
- Co-founded a registered student organization, worked out budgetary plans and led club members to raise funds
- Organized many landmark events including Quad Day, holding speeches from graduates who go to medical schools

# SKILLS
Computer Skills: Proficient in R, Tableau, GitHub, Microsoft Office Suite, etc.






